### ISSUE TITLE
when i run demo.ipnb,there is a alamr: no module named kalmanfilter? what can i do? pip install pyfilter?

### ISSUE THREAD

**Issue by miaozujia** [motokimura/kalman_filter_witi_kitti#1]
![image](https://user-images.githubusercontent.com/57306138/162920212-0ee84925-41e8-4e4e-906e-14622b376b34.png)

**Comment by motokimura** [comment]
Don't comment out `sys.path.append('./scr')` because `ExtendedKalmanFileter` class is defined at `src/kalman_filters/extended_kalman_filter.py`

pyfilter is not used at all in this repository since all the kalman filter logic is implemented from scratch under `src/`.
