### ISSUE TITLE
Theta slow convergence

### ISSUE THREAD

**Issue by aaman-ee** [motokimura/kalman_filter_witi_kitti#2]
Hi, thanks for the good EKF implementation. However, I noticed that the theta estimation shows a significant convergence delay. How this can be improved? 

![download](https://github.com/motokimura/kalman_filter_witi_kitti/assets/22389033/e0e324dd-a8a3-4934-a354-237d31c78913)

**Comment by motokimura** [comment]
It may be solved by adjusting covariance matrices Q (measurement noise covariance) & R (state transition noise covariance).
Generally, smaller Q and larger R make the convergence faster, but the filter become sensitive to the observation noise.
You need to find out the best values for your data.
Good luck!
