### ISSUE TITLE
R_ and self.P

### ISSUE THREAD

**Issue by Janudis** [motokimura/kalman_filter_witi_kitti#3]
Hello and congrats for your job. I want to ask two questions.
1) In the Kalman filter main routine, you do this: R_ = R * (dt ** 2.) but you dont use the R_
2) Based on the book Probabilistic Robotics, the resulting covariance in the update step is given by: Σt = (I − Kt Ht) Σ¯t (3.62)
However in your code, is given by: self.P = self.P - K @ H @ self.P. Shouldn't be self.P = I - K @ H @ self.P?

Thank you in advance.

**Comment by motokimura** [comment]
> 2\. Based on the book Probabilistic Robotics, the resulting covariance in the update step is given by: Σt = (I − Kt Ht) Σ¯t (3.62)
>     However in your code, is given by: self.P = self.P - K @ H @ self.P. Shouldn't be self.P = I - K @ H @ self.P?

My implementation should be correct because Σ¯t is multiplied from the right side.

Σt = (I − Kt Ht) Σ¯t = Σ¯t − Kt Ht Σ¯t

**Comment by motokimura** [comment]
> 1. In the Kalman filter main routine, you do this: R_ = R * (dt ** 2.) What is the meaning of this?

This normalize R with dt.
From a practical perspective, I think you don't need to go deep into this.
Even without this, i.e., R_ = R, the filter should work as long as R value is correctly adjusted.

**Comment by Janudis** [comment]
I meant this, you created the R_ but you didn't use it. Okay thanks for answering, you can close the issue.
